export const CoreEvents = {
  FLOOR_STATE_CHANGED: 'floor.stateChanged',
  FLOOR_COMMITTED: 'floor.committed',
  FLOOR_FAILED: 'floor.failed',
  VARIABLE_SET: 'variable.set',
  VARIABLE_PROMOTED: 'variable.promoted',
  VARIABLE_DELETED: 'variable.deleted',
  MEMORY_CREATED: 'memory.created',
  MEMORY_UPDATED: 'memory.updated',
  MEMORY_DEPRECATED: 'memory.deprecated',
  MEMORY_DELETED: 'memory.deleted',
  MEMORY_INJECTION_FAILED: 'memory.injection_failed',
  MEMORY_PERSIST_FAILED: 'memory.persist_failed',
  MEMORY_CONSOLIDATION_CONTEXT_FAILED: 'memory.consolidation_context_failed',
  MEMORY_CONSOLIDATION_JSON_PARSE_FAILED: 'memory.consolidation_json_parse_failed',
  MEMORY_CONSOLIDATED: 'memory.consolidated',
  MEMORY_CONSOLIDATION_FAILED: 'memory.consolidation_failed',
  MEMORY_EDGE_CREATED: 'memory.edge.created',
  MEMORY_EDGE_DELETED: 'memory.edge.deleted',
  TOOL_CALL_STARTED: 'tool.call_started',
  TOOL_CALL_COMPLETED: 'tool.call_completed',
  TOOL_CALL_FAILED: 'tool.call_failed',
  TOOL_CALL_DENIED: 'tool.call_denied',
} as const;
